version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  
  
  web:
    build: ./assessement
    command: python /code/manage.py runserver 0.0.0.0:8000 
    env_file:
      - ./.env
    
    volumes:
      - ./assessement:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
